FROM maven:3.8.3-openjdk-17 AS build
COPY . .
RUN mvn clean package

FROM openjdk:17.0.1-jdk-slim
COPY --from=build build/target/MyDelight-1.0-SNAPSHOT.jar MyDelight.jar
ENTRYPOINT ["java", "-jar", "MyDelight.jar"]
EXPOSE 8080